name: Black Formatter

on:
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black .

    - name: Check for changes
      id: changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "##[set-output name=changes_detected;]true"
        else
          echo "##[set-output name=changes_detected;]false"
        fi

    - name: Commit changes
      if: steps.changes.outputs.changes_detected == 'true'
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "chore: \`black .\`"
        git push
